# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_domain_name', models.CharField(max_length=1)),
                ('vchr_token', models.CharField(max_length=100)),
                ('vchr_pin_code', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
