# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabdata',
            name='vchr_pin_code',
        ),
    ]
